### ISSUE TITLE
含{{gameconsole}}模板提名异常

### ISSUE THREAD

**Issue by ChestnutLUO** [Nigh/laohuangli-lite-go#64]
<img width="645" alt="Xnip2024-03-13_10-06-06" src="https://github.com/Nigh/laohuangli-lite-go/assets/108659793/e5fe39cd-ee4b-42b7-a946-0a2e71acb04c">

**Comment by ChestnutLUO** [comment]
怀疑与 {{game}}有相同前缀有关

**Comment by ChestnutLUO** [comment]
<img width="660" alt="图片" src="https://github.com/Nigh/laohuangli-lite-go/assets/108659793/e85dc076-0f1e-43c0-b968-55a1fa00e079">
补充测试

**Comment by ChestnutLUO** [comment]
https://github.com/Nigh/laohuangli-lite-go/blob/c0ac70c3dc63c84ce9cc5043eec3a5050d55a708/tgbot/nominate.go#L201
长度控制 和 不存在模板检查工作正常

**Comment by ChestnutLUO** [comment]
require label #Bug

**Comment by ChestnutLUO** [comment]
{{transportwo}} 与 {{transport}} 同样出现问题

**Comment by Nigh** [comment]
已确认为转义相关问题。
